### PR TITLE
Add gradient to loader

### PR DESCRIPTION
**Pull request by hearsilent**
- Upgrade gradle to 2.1.3
- Update Bintray & Maven gradle plugin
- Add gradient to loader (Attribute setting)
- Improve performance

### CODE REVIEW

**Comment by hearsilent** [comment]
device-2016-08-29-124044

**Comment by elye** [comment]
Thanks Hearsilent.

When I try to sync using Android Studio 2.0 and even 2.2, it has the below error
`Error:(3, 0) No service of type Factory<LoggingManagerInternal> available in ProjectScopeServices.`

Seems like upgrade to `gradle-2.14.1-all.zip` and build:gradle:2.1.3 is causing some issue.

Also, if you like to have the gradient, maybe it would be good as an attribute setting. As the direct plain color is preferred by others thus far.

Cheers.

**Comment by hearsilent** [comment]
@elye Got it! I will add attribute setting, and downgrade gradle.

**Comment by hearsilent** [comment]
@elye 

I've added attribute setting.
And I found the issue is maven gradle plugin too old,
so I just update Bintray & Maven gradle plugin.

You can see the finally effect like this.


I've add sample to README and sample project.
BTW, you can use  demo mode (Developer options) to make library preview more pretty.


Or you can use https://play.google.com/store/apps/details?id=com.emmaguy.cleanstatusbar to make a clean status bar when capturing the screen.

Cheers.

**Comment by elye** [comment]
Thanks. LGTM.

**Pull request merged**
